### PR TITLE
Make contributing to docs easier

### PR DESCRIPTION
**Pull request by daertommy**
With this PR readers can suggest changes to the docs with an easy to use WYSIWYG markdown editor.

[This](https://holocron.so/github/pr/heluxjs/helux/master/editor) is how the editor looks like for this repo.

https://github.com/remorses/docusaurus-example/assets/31321188/43c8bc68-3668-4a25-bf1c-a70eceab7bcb

### CODE REVIEW

**Comment by fantasticsoul** [comment]
cool，I will try this feature in the coming days

**Comment by daertommy** [comment]
Let me know if you have any feedback or find any bugs!

**Comment by fantasticsoul** [comment]
no problem，thx a lot.

**Review by fantasticsoul — APPROVED** [review]
lgtm

**Pull request merged**
